CREATE extension IF NOT EXISTS  "uuid-ossp";

INSERT INTO "user" (user_id, username, name, password) VALUES
(uuid_generate_v4(), 'achernyshova@salesforce.com', 'Anastasia Chernyshova', 'achernyshova'),
(uuid_generate_v4(), 'achopda@salesforce.com', 'Archana Chopda', 'achopda'),
(uuid_generate_v4(), 'archanasinha@salesforce.com', 'Archana Sinha', 'archanasinha'),
(uuid_generate_v4(), 'bkyle@salesforce.com', 'Brendan Kyle', 'bkyle'),
(uuid_generate_v4(), 'bbanville@salesforce.com', 'Brona Banville', 'bbanville'),
(uuid_generate_v4(), 'cinnes@salesforce.com', 'Carrie Innes', 'cinnes'),
(uuid_generate_v4(), 'csellaro@salesforce.com', 'Connie Sellaro', 'csellaro'),
(uuid_generate_v4(), 'edna.tan@salesforce.com', 'Edna Tan', 'edna.tan'),
(uuid_generate_v4(), 'hykwan@salesforce.com', 'Heng Kwan', 'hykwan'),
(uuid_generate_v4(), 'ivy.ng@salesforce.com', 'Ivy Ng', 'ivy.ng'),
(uuid_generate_v4(), 'jpok@salesforce.com', 'Jo Pok', 'jpok'),
(uuid_generate_v4(), 'klauw@salesforce.com', 'Karen Lauw', 'klauw'),
(uuid_generate_v4(), 'kabhishek@salesforce.com', 'Kavea Kabhishek', 'kabhishek'),
(uuid_generate_v4(), 'kritika.srinivasan@salesforce.com', 'Kritika Srinivasan', 'kritika.srinivasan'),
(uuid_generate_v4(), 'lisa.noble@salesforce.com', 'Lisa Noble', 'lisa.noble'),
(uuid_generate_v4(), 'mdhawan@salesforce.com', 'Madhur Dhawan', 'mdhawan'),
(uuid_generate_v4(), 'mthistleton@salesforce.com', 'Maggie Thistleton', 'mthistleton'),
(uuid_generate_v4(), 'mwilliamson@salesforce.com', 'Mairi Williamson', 'mwilliamson'),
(uuid_generate_v4(), 'mcolak@salesforce.com', 'Marisa Colak', 'mcolak'),
(uuid_generate_v4(), 'michelle.lim@salesforce.com', 'Michelle Lim', 'michelle.lim'),
(uuid_generate_v4(), 'nnehme@salesforce.com', 'Naomi Nehme', 'nnehme'),
(uuid_generate_v4(), 'nathan.walsh@salesforce.com', 'Nathan Walsh', 'nathan.walsh'),
(uuid_generate_v4(), 'nichola.palmer@salesforce.com', 'Nichola Palmer', 'nichola.palmer'),
(uuid_generate_v4(), 'npeers@salesforce.com', 'Nick Peers', 'npeers'),
(uuid_generate_v4(), 'pmandavia@salesforce.com', 'Prina Mandavia', 'pmandavia'),
(uuid_generate_v4(), 'boramakrishna@salesforce.com', 'Bhargav Oruganti', 'boramakrishna'),
(uuid_generate_v4(), 'rbertram@salesforce.com', 'Renata Bertram', 'rbertram'),
(uuid_generate_v4(), 'sam.kong@salesforce.com', 'Sam Kong', 'sam.kong'),
(uuid_generate_v4(), 'shargreaves@salesforce.com', 'Sarah Hargreaves', 'shargreaves'),
(uuid_generate_v4(), 'sbarboza@salesforce.com', 'Savannah Barboza', 'sbarboza'),
(uuid_generate_v4(), 'smccredie@salesforce.com', 'Stephanie McCredie', 'smccredie'),
(uuid_generate_v4(), 'stephanie.mcmillan@salesforce.com', 'Stephanie McMillan', 'stephanie.mcmillan'),
(uuid_generate_v4(), 'sfrank@salesforce.com', 'Stuart Frank', 'sfrank'),
(uuid_generate_v4(), 'taleah.jones@salesforce.com', 'Taleah Jones', 'taleah.jones'),
(uuid_generate_v4(), 'trina.ng@salesforce.com', 'Trina Ng', 'trina.ng'),
(uuid_generate_v4(), 'vcotte@salesforce.com', 'Vincent Cotte', 'vcotte'),
(uuid_generate_v4(), 'alexandra.campbell@salesforce.com', 'Alexandra Campbell', 'alexandra.campbell'),
(uuid_generate_v4(), 'amy.ong@salesforce.com', 'Amy Ong', 'amy.ong'),
(uuid_generate_v4(), 'angela.ward@salesforce.com', 'Angela Ward', 'angela.ward'),
(uuid_generate_v4(), 'ateoh@salesforce.com', 'Adeline Teog', 'ateoh'),
(uuid_generate_v4(), 'bdemets@salesforce.com', 'Bianka Demets', 'bdemets'),
(uuid_generate_v4(), 'dhawkins@salesforce.com', 'Demi Hawkins', 'dhawkins'),
(uuid_generate_v4(), 'gdjuardi@salesforce.com', 'Grace Djuardi', 'gdjuardi'),
(uuid_generate_v4(), 'katejones@salesforce.com', 'Kate Jones', 'katejones'),
(uuid_generate_v4(), 'nvaneijk@salesforce.com', 'Nathalie Van Eijk', 'nvaneijk'),
(uuid_generate_v4(), 'rgurumurthy@salesforce.com', 'RK Gurumurthy', 'rgurumurthy'),
(uuid_generate_v4(), 'rheuston@salesforce.com', 'Rebecca Heuston', 'rheuston'),
(uuid_generate_v4(), 's.chattopadhyay@salesforce.com', 'Surjasnata Chattopadhyay', 's.chattopadhyay'),
(uuid_generate_v4(), 'sleu@salesforce.com', 'Stefanie Leu', 'sleu'),
(uuid_generate_v4(), 'wsakaris@salesforce.com', 'William Sakaris', 'wsakaris'),
(uuid_generate_v4(), 'yingyi.wan@salesforce.com', 'Ying Yi Wan', 'yingyi.wan'),
(uuid_generate_v4(), 'ndickson@salesforce.com', 'Nikki Dickson', 'ndickson');