swagger: '2.0'
info:
  description: SARA REST API definition
  version: 1.0.0
  title: SARA (Sales Reporter Applicaltion) REST services
  contact:
    email: miller.gonzalez@globant.com

paths:
  /api-status:
    get:
      x-swagger-router-controller: status
      operationId: "getInfo"
      summary: Returns 200 if the api is running
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
        default:
          description: Invalid request.
          schema:
            allOf: 
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

  #FORMS  
  /program:
    get:
      x-swagger-router-controller: program
      operationId: "getPrograms"
      summary: Returns the list of probrams.
      description: This will be used to populate the insert and update dropdowns
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/ProgramListResponse'
        default:
          description: Invalid request.
          schema:
            allOf: 
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

  /programs/{userId}:
    get:
      x-swagger-router-controller: program
      operationId: "getProgramsFull"
      summary: Returns the list of programs.
      description: This will be used to populate the activity table
      parameters:
        - in: path
          name: userId
          description: ID of user to fetch programs
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/ProgramListResponse'
        default:
          description: Invalid request.
          schema:
            allOf: 
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'
  
  /region:
    get:
      x-swagger-router-controller: region
      operationId: "getRegion"
      summary: Returns the list of regions.
      description: This will be used to populate the insert and update dropdowns
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/RegionListResponse'
        default:
          description: Invalid request.
          schema:
            allOf: 
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

  /format/{tacticId}:
    get:
      x-swagger-router-controller: format
      operationId: "getFormatsByTacticId"
      summary: Returns the list of formats filtered by tacticId.
      parameters:
        - in: path
          name: tacticId
          description: ID of tactic to fetch
          required: true
          type: string
      description: This will be used to populate the insert and update dropdowns
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/FormatListResponse'
        default:
          description: Invalid request.
          schema:
            allOf: 
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

  /tactic:
    get:
      x-swagger-router-controller: tactic
      operationId: "getTactics"
      summary: Returns the list of tactics.
      description: This will be used to populate the insert and update dropdowns
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/TacticListResponse'
        default:
          description: Invalid request.
          schema:
            allOf: 
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

  #REPORTS
  /activity:  
    post:
      x-swagger-router-controller: activity
      operationId: "addNewActivity"
      summary: Create a new activity
      description: N/A
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ActivityCreateBody'
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
        default:
          description: Invalid request.
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'
    delete:
      x-swagger-router-controller: activity
      operationId: "deleteActivity"
      summary: Delete an activity
      description: N/A
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/DeleteActivity'
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
        default:
          description: Invalid request.
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

  /activities/{userId}:
    get:
      x-swagger-router-controller: activity
      operationId: "getActivities"
      summary: Returns the list of activities by user.
      description: This will be used to populate the activities table
      parameters:
        - in: path
          name: userId
          description: ID of user to fetch activities
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/ProgramListResponse'
        default:
          description: Invalid request.
          schema:
            allOf: 
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

  /activity/{id}:  
    get:
      x-swagger-router-controller: activity
      operationId: "getActivityById"
      summary: get an activity by id
      description: N/A
      parameters:
        - in: path
          name: id
          description: ID of activity to fetch
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/ActivityResponse'
        default:
          description: Invalid request.
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'
    
    put:
      x-swagger-router-controller: activity
      operationId: "updateActivity"
      summary: Update an activity by id
      parameters:
        - in: path
          name: id
          description: ID of activity to update
          required: true
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/ActivityCreateBody'
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
        default:
          description: Invalid request.
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

  /login:
    post:
      x-swagger-router-controller: user
      operationId: "doLogin"
      summary: Returns login ok if the pwd and user match
      description: Used temporaly for the login endpoint
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/DoLoginBody'
      responses:
        200:
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/ResponseStatus'

        default:
          description: Invalid request.
          schema:
            allOf: 
              - $ref: '#/definitions/ResponseStatus'
              - $ref: '#/definitions/Error'

#RESPONSES
definitions:
  ActivityCreateBody:
    description: Body used for creating a new activity.
    type: object
    properties:
      activityId:
        type: string
      title:
        type: string
      campaignId:
        type: string
      tacticId:
        type: string
      formatId:
        type: string
      abstract:
        type: string
      regionId:
        type: string
      startDate:
        type: string
      endDate:
        type: string
      asset:
        type: string
      userId:
        type: string
      programId:
        type: string
  
  DeleteActivity:
    description: Body used for deleting one or more activities.
    type: object
    properties:
      activitiesId:
        type: array
        items:
          type: string


  ProgramListResponse:
    description: A list of programs.
    type: object
    properties:
      result:
        type: array
        items:
          $ref: '#/definitions/Program'

  activityListResponse:
    description: a list of activities.
    type: object
    properties:
      result:
        type: array
        items:
          $ref: '#/definitions/Activity'
                    
  FormatListResponse:
    description: A list of formats.
    type: object
    properties:
      result:
        type: array
        items:
          $ref: '#/definitions/Format'

  TacticListResponse:
    description: A list of tactics.
    type: object
    properties:
      result:
        type: array
        items:
          $ref: '#/definitions/Tactic'

  RegionListResponse:
    description: A list of users.
    type: object
    properties:
      result:
        type: array
        items:
          $ref: '#/definitions/Region'

  ResponseStatus:
    type: object
    properties:
      info:
        description: The object containing the HTTP status for the response.
        type: object
        properties:
          status:
            description: The numeric HTTP status code for the response.
            type: integer
            example: Status HTTP Code
          code:
            description: The textual HTTP status code for the response.
            type: string
            example: OK
        required:
          - status
          - code

  ActivityResponse:
    description: Single activity
    type: object
    properties:
      result:
        $ref: '#/definitions/Activity'
          

  DoLoginBody:
    description: Body used for creating a new user.
    type: object
    properties:
      username:
        type: string
      password:
        type: string
        
  
  Error:
    properties:
      message:
        type: string
    required:
      - message
  
  #MODELS     
  Activity:
    type: object
    properties:
      title:
        type: string
      campaignId:
        type: string
      tacticId:
        type: string
      formatId:
        type: string
      abstract:
        type: string
      regionId:
        type: string
      startDate:
        type: string
      endDate:
        type: string
      asset:
        type: string
      userId:
        type: string
      programId:
        type: string

  Program:
    type: object
    properties:
      program_id:
        type: string
      label:
        type: string
        
  Format:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      label:
        type: string

  Tactic:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      label:
        type: string
              
  Region:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      label:
        type: string

  Status:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      name:
        type: string
            
schemes: ['http', 'https']
consumes: ['application/json']
produces: ['application/json']

host: localhost:3000
basePath: /api/v1